name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Buildx para construir imágenes Docker (opcional pero recomendado)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Construir y subir la imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile  # Asegúrate de que el Dockerfile esté en la raíz o ajusta la ruta
          push: true
          tags: eriksonlives/front-react:latest

      # 5. Conectarse a la instancia EC2 para desplegar la nueva imagen
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}         # IP o dominio de la EC2
          username: ${{ secrets.EC2_USERNAME }}   # Usualmente "ubuntu" en EC2 con Ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}         # Clave privada en un secreto
          script: |
            cd /home/ubuntu/deploy    # Directorio donde se encuentra el docker-compose.yml
            docker-compose pull front-react
            docker-compose up -d --no-deps front-react
