name: Continuous Deployment

on:
  push:
    branches:
      - erikson # O la rama que utilices para el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio central (contiene docker-compose.yml, react, etc.)
      - name: Checkout central repository
        uses: actions/checkout@v3

      # 2. Checkout del repositorio de auth-service (por ejemplo, spring-boot-proyect)
      - name: Checkout auth-service repository
        uses: actions/checkout@v3
        with:
          repository: eriksonlive/spring-boot-proyect
          path: auth-service

      # 3. Checkout del repositorio del gateway (client-gateway)
      - name: Checkout client-gateway repository
        uses: actions/checkout@v3
        with:
          repository: eriksonlive/gateway-nest
          path: micro/client-gateway

      # 4. Checkout del repositorio de orders-ms
      - name: Checkout orders-ms repository
        uses: actions/checkout@v3
        with:
          repository: eriksonlive/orders-ms-nest
          path: micro/orders-ms

      # 5. Checkout del repositorio de products-ms
      - name: Checkout products-ms repository
        uses: actions/checkout@v3
        with:
          repository: eriksonlive/products-ms-nest
          path: micro/products-ms

      # 6. (Opcional) Configurar Buildx para Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 7. Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 8. Construir y subir las imágenes a partir del docker-compose
      - name: Build and push Docker images
        run: |
          docker compose build
          docker compose push

      # 9. Despliegue en el VPS (o en el servidor de Hostinger)
      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOSTINGER_HOST }} # IP o dominio de tu VPS
          username: ${{ secrets.HOSTINGER_USER }} # Usuario en el VPS
          key: ${{ secrets.HOSTINGER_PASS }} # Clave privada (asegúrate de que sea la adecuada)
          port: 22
          script: |
            cd /var/www/energytalento.tech    # Directorio en el VPS donde está el docker-compose.yml
            docker compose pull
            docker compose up -d --remove-orphans
